name: live_stream
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  agora_rtc_engine: ^6.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  permission_handler: ^11.2.0
  starlight_utils:
    git:
      url: https://github.com/YeMyoAung/starlight_utils.git
  get_it: ^7.6.7
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_app_check: ^0.2.1+8
  google_sign_in: ^6.2.1
  lottie: ^3.0.0
  community_material_icon: ^5.9.55
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
